# Generated by Django 4.2.3 on 2023-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_appointment_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('notes', models.CharField(max_length=5000)),
                ('users', models.ManyToManyField(to='home.user')),
            ],
        ),
    ]
