# Generated by Django 4.2.3 on 2023-07-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(default='./DefaultProfilePic.jpg', upload_to='profilePictures/'),
        ),
    ]
