# Generated by Django 4.2.3 on 2023-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(default='/home/DefaultProfilePic.jpg', upload_to='profilePictures/'),
        ),
    ]
