# Generated by Django 4.2.3 on 2023-08-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(default='/media/profilePictures/DefaultProfilePic.png', upload_to='profilePictures/'),
        ),
    ]
