# Generated by Django 4.2.3 on 2023-08-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='temp/')),
            ],
        ),
    ]
