# Generated by Django 4.2.3 on 2023-08-15 15:37

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tempimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(default='/media/profilePictures/DefaultProfilePic.png', upload_to=home.models.upload_path),
        ),
    ]
